import { GetStaticPaths, GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import React from 'react';
import { BsFillCartPlusFill } from 'react-icons/bs';
import { Product, Products } from '../../model/product';

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch('http://localhost:3000/api/products');
  const data = await res.json();

  return {
    props: { products: data },
  };
};

export const getStaticPaths: GetStaticPaths = async () => {
  const res = await fetch('http://localhost:3000/api/products');
  const data = await res.json();

  const paths = data.map((product: { id: { toString: () => Product } }) => {
    console.log(product);
    return {
      params: { id: product.id.toString() },
    };
  });
  return {
    paths,
    fallback: false,
  };
};

const ProductDetails = ({ products }: Products) => {
  const router = useRouter();
  const detailsId = router.query.id;
  const detailsData = products.find((product) => product.id == detailsId);

  return (
    <div>
      <Head>
        <title>Product | E - Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center mt-12">
        <Image src={detailsData?.img} alt="image" width={300} height={300} />
        <p className="text-3xl">Details of {detailsData?.name}</p>
        <p className="text-3xl">Price : ${detailsData?.price}</p>
        <p className="text-xl mx-72">
          Description : {detailsData?.description}
        </p>
        <p className="text-2xl">Product Available : 10</p>
        <div className="flex justify-center mt-2">
          <button className="px-6 py-2 transition ease-in duration-200 uppercase rounded-full hover:bg-gray-800 hover:text-white border-2 border-gray-900 focus:outline-none flex items-center">
            <BsFillCartPlusFill />
            <p className="ml-2">Add to cart</p>
          </button>
        </div>
      </div>
    </div>
  );
};

export default ProductDetails;
