import Head from 'next/head';
import React from 'react';
import { GetStaticProps } from 'next';
import ProductList from '../../components/product/ProductList';
import { Products } from '../../model/product';

export const getStaticProps: GetStaticProps = async () => {
    const res = await fetch('http://localhost:3000/api/products');
    const data = await res.json()
   
    return { 
        props: { products: data }
    }
}

const productList = ({products}: Products) => {
    return (
        <div>
            <Head>
                <title>Product List | E - Cart</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <ProductList products={products}/>
            </div>
        </div>
    );
};

export default productList;
