import Head from 'next/head';
import React from 'react';
import Checkout from '../components/Checkout';

const checkout = () => {
  return (
    <div>
      <Head>
        <title>Checkout | E - Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Checkout />
    </div>
  );
};

export default checkout;