import Head from 'next/head';
import React from 'react';
import MyOrders from '../components/MyOrders';

const myOrders = () => {
  return (
    <div>
      <Head>
        <title>Cart | E - Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyOrders />
      
    </div>
  );
};

export default myOrders;
