import Head from 'next/head';
import React from 'react';
import ProductList from '../components/ProductList';

const productList = () => {
    return (
        <div>
            <Head>
                <title>Product List | E - Cart</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <ProductList />
            </div>
        </div>
    );
};

export default productList;
